name: coremobiledemo
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  provider: ^4.0.4
  cupertino_icons: ^0.1.2
  transparent_image: ^1.0.0
  photo_view: ^0.9.1
  loading: ^1.0.2
  easy_localization: ^2.1.0+2
  page_indicator: ^0.3.0
  rxdart: ^0.23.1
  fluttertoast: ^3.1.3
  flutter_statusbar_text_color: ^0.1.2
  json_annotation:
  http:
  permission_handler: ^4.4.0
  flutter_google_places: ^0.2.3
  sticky_headers: ^0.1.8
  progress_dialog: ^1.2.1
  dartz: ^0.8.9
  mime_type: ^0.2.6
  random_string: ^2.0.1
  location: ^2.5.0
  encrypt: ^4.0.0
  device_info: ^0.4.1+5
  material_design_icons_flutter: ^4.0.5045
  flutter_image_compress: ^0.6.5+1
  flutter_rounded_date_picker: 1.0.0
  pull_to_refresh: ^1.5.8
  flutter_sticky_header: ^0.4.2
  charts_flutter: ^0.9.0
  html: ^0.14.0+3
  webview_flutter: ^1.0.7
  flutter_slidable: ^0.5.4
  get_version: ^0.2.2
  url_launcher: ^5.7.10
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  json_serializable:


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/langs/en.json
    - assets/langs/vi.json
    - assets/imgs/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
